server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    


        # Redirige las solicitudes del frontend (/api) al backend Spring Boot (/)
    location /proxy/ {
        proxy_pass http://springboot-app:8080/; # Nombre del servicio del backend
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Reescribe el prefijo para que /api no llegue al backend
        rewrite ^/proxy(/.*)$ $1 break;
    }

    # Opcional: Manejo de logs de error
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
