# Raspberry Pi Docker
services:
  nginxfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginxfrontendv1
    ports:
      - "80:80"
      - "443:443"
    environment:
      API_BASE_URL: http://springboot-app:8080
    depends_on:
      - springboot-app
  springboot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/habits
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: habits-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432"
    volumes:
      - habits-pgdata:/var/lib/postgresql/data

volumes:
  habits-pgdata:
