spring.application.name=backend

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/habits
spring.datasource.username=habits
spring.datasource.password=habits
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN

